import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import wasm from 'vite-plugin-wasm';
import path from 'node:path';

// The wasm / onchain-runtime handling below is taken from Midnight's official
// bboard UI template. Getting the Compact runtime's wasm to load in a browser
// bundle is fiddly; this configuration is known-good and should not be
// "simplified".
const repoRoot = path.resolve(import.meta.dirname, '..');
const contractDir = path.resolve(repoRoot, 'contracts', 'managed', 'aegis');

export default defineConfig({
  cacheDir: './.vite',
  resolve: {
    alias: {
      // The contract API generated by `compact compile`, imported straight
      // from the repo root so the UI and the tests share one source of truth.
      '@aegis/contract': path.resolve(contractDir, 'contract', 'index.js'),
      // The very same simulator and witness implementations the devnet tests
      // run against — the UI gets no private copy of privacy-critical code.
      '@aegis/simulator': path.resolve(repoRoot, 'src', 'simulator.ts'),
      '@aegis/chain': path.resolve(repoRoot, 'src', 'chain.ts'),
      '@aegis/demo-data': path.resolve(repoRoot, 'src', 'demo-data.ts'),
      '@aegis/witnesses': path.resolve(repoRoot, 'src', 'witnesses.ts'),
      '@aegis/private-state': path.resolve(repoRoot, 'src', 'private-state.ts'),
      // Network endpoints, shared with the scripts so the browser cannot drift
      // to a different indexer than the one the deploy wrote about.
      '@aegis/config': path.resolve(repoRoot, 'src', 'config.ts'),
    },
    extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json', '.wasm'],
    mainFields: ['browser', 'module', 'main'],
  },
  server: {
    port: 5173,
    fs: {
      // Allow importing the compiled contract from outside the ui/ root.
      allow: [repoRoot],
    },
  },
  build: {
    target: 'esnext',
    minify: false,
    rollupOptions: {
      output: {
        manualChunks: (id: string) => {
          if (id.includes('onchain-runtime-v3')) return 'wasm';
        },
      },
    },
    commonjsOptions: {
      transformMixedEsModules: true,
      extensions: ['.js', '.cjs'],
      ignoreDynamicRequires: true,
    },
  },
  plugins: [
    react(),
    // Note: vite-plugin-top-level-await is deliberately NOT used. It requires
    // rollup and esbuild as unlisted peers (the bboard template only satisfies
    // them by accident of an unrelated plugin), and with build.target 'esnext'
    // the browser handles the Compact runtime's top-level await natively.
    wasm(),
  ],
  optimizeDeps: {
    include: ['@midnight-ntwrk/compact-runtime'],
    exclude: [
      '@midnight-ntwrk/onchain-runtime-v3',
      '@midnight-ntwrk/onchain-runtime-v3/midnight_onchain_runtime_wasm_bg.wasm',
      '@midnight-ntwrk/onchain-runtime-v3/midnight_onchain_runtime_wasm.js',
    ],
  },
});
